sudo: false
language: objective-c # test on OSX
env:
  global:
    - NODE_VERSION=6
    - CC=clang
    - CXX=clang++
before_install:
  # Node.js
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm
  - source /tmp/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use --delete-prefix $NODE_VERSION
  # Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn install
script:
  - yarn test
notifications:
  slack:
    secure: "Kqf/0ZTR7RkrFGc7ASkAtMtTS2Qcqgxnrh2z8AdLruPE8fgtrrS+JdE2RQozefO6HF/kYZ1zVG/PoJMX1JjyT0+oekBCSP4RfU6mckdB3HaQmwtGm0E1OMQftvAMQvLxNHqOJ/51lALG/DJgnbmplkaWZyTGFoxo75nwG2M/3onWK33IyBpI6j28MvUUPYz0VDmbvREVIDPVYdOnfb4xeg+t9sHy6h4bRn5XVaMyzR+m8bfDJKBq7XY/RXbK6y+81GEQeU++23GAtxoIOzWZrF0FZc96ngYizkgqitVQ57ZNwna61k+b1mPxawjarD7dGOmD8C1HBKGZiO0jjGeXPHh9GdvYo9L1P0ewjHgQkSQIcFOEVk8VMSx9u0CDdNi3Poq4CeD/HUObTBJGnjmmv/5DBTvtZ55c2chZ5DCL2AgHTSdoYVfCW1pDzJgtK6ZT2f0kAjWUsphldDfQcQSHFR8N4Ne3YvHe3CiFrrRx7cTW9Yn8mEZEMxbqXIhOe5Xrj/tN43xNLjqyjaJb67Vd4kZwELLkwXfe2ndMYNjm42MHL1n7/GnrGsVirGm0az99t0guUKI1lG5GTKHAaxV5veu4E8weHIqM4IvVWIBacHPm5YBwfExTNcloPvj1DdHtX3PO51278saixQVk3AIUiqQ6soDrGrzJw7DCu5Cvemk="
